version: '3.9'
services:
  server:
    image: node:latest
    volumes:
      - ./:/code
    container_name: server
    restart: always
    ports:
      - 3000:8080
    command: ["bin/bash"]
    stdin_open: true
    tty: true